# Generated by Django 3.2.12 on 2023-12-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('psevdonim', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('created_at', models.DateField()),
                ('genre', models.CharField(max_length=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='item.author')),
            ],
        ),
    ]
